import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import { SideNavigation } from "@/components/common";
import { Toaster } from "@/components/ui"
// 전역 css
import "@/styles/globals.css";
import "@/styles/main.scss";

const NOTO_SANS_KR = Noto_Sans_KR({subsets: ["latin"]});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shadcn UI - TODO-TASKBOARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <div className="page">
          <SideNavigation />
          <main className="page__main">{children}</main>
        </div>
        <Toaster />
    </>
  );
}
