import type { Metadata } from "next";
import { SideNavigation } from "@/components/common";
import { Toaster } from "@/components/ui"
// 전역 css
import "@/styles/globals.css";
import "@/styles/main.scss";

export const metadata: Metadata = {
  title: "Shadcn UI - TODO-TASKBOARD",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <div className="page">
          <SideNavigation />
          <main className="page__main">{children}</main>
        </div>
        <Toaster />
    </>
  );
}
