import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { Toaster } from "@/components/ui"
// 전역 css
import "@/styles/globals.css";
import "@/styles/main.scss";

const NOTO_SANS_KR = Noto_Sans_KR({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Shadcn UI - TODO-TASKBOARD",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
        <body className={NOTO_SANS_KR.className}>
            {children}
            <Toaster />
        </body>
    </html>
  );
}
